### ISSUE TITLE
Could you please offer the construct code of "noise-TACRED"?

### ISSUE THREAD

**Issue by SiriYXR** [rtmaww/SENT#13]
I have successfully reproduced the code on the ARNOR data set, and want to further experiment on the noise-TACRED dataset. I have applied for the TACRED dataset from LCD, if you can provide the noise-TACRED construction code will be very thankful.

**Comment by lj564** [comment]
> 

Me too. Confused.

**Comment by rtmaww** [comment]
Hello. Could you please provide an E-mail address so I can send it to you?

**Comment by lj564** [comment]
564215385@qq.com

**Comment by SiriYXR** [comment]
> Hello. Could you please provide an E-mail address so I can send it to you?

1158737962@qq.com 

Thank you very much!

**Comment by XuYuxuan-git** [comment]
> Hello. Could you please provide an E-mail address so I can send it to you?

84764015@qq.com

Thanks!

**Comment by UNITYli** [comment]
> Hello. Could you please provide an E-mail address so I can send it to you?

2373515564@qq.com  I'm very interested in your work ，thank you

**Comment by Emma1066** [comment]
Is this file in the scripts directory the construct code of "noise-TACRED" ?
[https://github.com/rtmaww/SENT/blob/master/scripts/tacred2nyt_randomrelabel.py](url)
